version: "3.1"
services:
  db:
    env_file:
      - .env
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - 3306:3306

  admin:
     image: adminer
     ports:
       - 8080:8080
